# Generated by Django 5.1.2 on 2024-11-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=60)),
                ('loan_amt', models.IntegerField()),
                ('cust_name', models.CharField(max_length=60)),
                ('cust_acno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
